# ./docker-compose.yml

version: '2'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hola_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "9906:3306"
  php:
    image: php:7.2-apache
    container_name: php
    depends_on:
      - mysql
    volumes:
      - ./apps/:/var/www/html/
    ports:
      - "5000:80"
  composer:
    image: composer/composer:php7
    command: install
