user_api_create:
    path: /api/1.0/create
    controller: AppBundle\Controller\UserAPIController::create
    methods: POST

user_api_retrieve:
    path: /api/1.0/retrieve/{id}
    controller: AppBundle\Controller\UserAPIController::retrieve
    methods: POST

user_api_update:
    path: /api/1.0/update/{id}
    controller: AppBundle\Controller\UserAPIController::update
    methods: PUT

user_api_delete:
    path: /api/1.0/delete/{id}
    controller: AppBundle\Controller\UserAPIController::delete
    methods: DELETE

