user_api_create:
    path:       /page/1
    controller: AppBundle\Controller\UserAPIController::page_1
    methods:    GET

page_2:
    path:       /page/2
    controller: AppBundle\Controller\PageController::page_2
    methods:    GET

