page_1:
    path: /page/1
    controller: AppBundle\Controller\PageController::page_1
    methods: GET

page_2:
    path: /page/2
    controller: AppBundle\Controller\PageController::page_2
    methods: GET
